import React from 'react';
import { Message, UserProfile } from '../types';
import { Copy, Check, ThumbsUp, ThumbsDown, Download, Globe } from 'lucide-react';

interface MessageBubbleProps {
  message: Message;
  darkMode: boolean;
  userProfile: UserProfile;
  onReaction: (messageId: string, reaction: 'like' | 'dislike') => void;
}

// Download functions
const downloadAsPDF = async (text: string, filename: string = 'green-ai-response.pdf') => {
  try {
    const content = `
GREEN AI Response
================

${text}

Generated by GREEN AI
${new Date().toLocaleString()}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.replace('.pdf', '.txt');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Download failed:', error);
  }
};

const downloadAsDoc = (text: string, filename: string = 'green-ai-response.doc') => {
  try {
    const content = `
<html>
<head>
<meta charset="utf-8">
<title>GREEN AI Response</title>
</head>
<body>
<h1>GREEN AI Response</h1>
<div style="white-space: pre-wrap; font-family: Arial, sans-serif; line-height: 1.6;">
${text.replace(/\n/g, '<br>')}
</div>
<hr>
<p><em>Generated by GREEN AI on ${new Date().toLocaleString()}</em></p>
</body>
</html>
    `.trim();

    const blob = new Blob([content], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Download failed:', error);
  }
};

const AIAvatar = () => (
  <div className="w-[30px] h-[30px] rounded-full bg-emerald-500 flex items-center justify-center flex-shrink-0 mt-0.5">
    <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round">
      <path d="M12 2L12 22M2 12L22 12" />
    </svg>
  </div>
);

const UserAvatar = ({ name }: { name: string }) => (
  <div className="w-[30px] h-[30px] rounded-full bg-indigo-500 flex items-center justify-center flex-shrink-0 mt-0.5 text-white text-xs font-medium">
    {name?.[0]?.toUpperCase() ?? 'U'}
  </div>
);

const renderMarkdown = (text: string, darkMode: boolean) => {
  return text.split('\n').reduce<React.ReactNode[]>((acc, line, i) => {
    const trimmed = line.trim();

    if (!trimmed) {
      acc.push(<div key={i} className="h-2" />);
      return acc;
    }

    if (/^#{1,3}\s/.test(trimmed)) {
      acc.push(
        <p key={i} className="font-medium text-[15px] mt-4 mb-1 first:mt-0">
          {trimmed.replace(/^#+\s/, '')}
        </p>
      );
      return acc;
    }

    if (/^[-*]\s/.test(trimmed)) {
      acc.push(
        <li key={i} className="ml-5 list-disc text-[15px] leading-relaxed mb-1">
          {inlineFormat(trimmed.replace(/^[-*]\s/, ''), darkMode)}
        </li>
      );
      return acc;
    }

    if (/^\d+\.\s/.test(trimmed)) {
      acc.push(
        <li key={i} className="ml-5 list-decimal text-[15px] leading-relaxed mb-1">
          {inlineFormat(trimmed.replace(/^\d+\.\s/, ''), darkMode)}
        </li>
      );
      return acc;
    }

    acc.push(
      <p key={i} className="text-[15px] leading-relaxed mb-3 last:mb-0">
        {inlineFormat(trimmed, darkMode)}
      </p>
    );
    return acc;
  }, []);
};

const inlineFormat = (text: string, darkMode: boolean): React.ReactNode => {
  const parts = text.split(/(`[^`]+`|\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('`') && part.endsWith('`')) {
      return (
        <code key={i} className={`font-mono text-[13px] px-1 py-0.5 rounded ${
          darkMode ? 'bg-gray-700 text-gray-200' : 'bg-gray-100 text-gray-800'
        }`}>
          {part.slice(1, -1)}
        </code>
      );
    }
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i} className="font-medium">{part.slice(2, -2)}</strong>;
    }
    return part;
  });
};

export const MessageBubble: React.FC<MessageBubbleProps> = ({
  message,
  darkMode,
  userProfile,
  onReaction,
}) => {
  const [copied, setCopied] = React.useState(false);
  const isUser = message.sender === 'user';

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(message.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      console.error('Copy failed', e);
    }
  };

  return (
    <div className={`group w-full transition-colors duration-150 ${
      darkMode ? 'hover:bg-gray-800/40' : 'hover:bg-gray-50/70'
    }`}>
      <div className={`max-w-3xl mx-auto px-4 py-3 flex gap-3 ${isUser ? 'flex-row-reverse' : ''}`}>

        {isUser
          ? <UserAvatar name={userProfile.name || 'U'} />
          : <AIAvatar />
        }

        <div className={`flex flex-col gap-1.5 max-w-[85%] ${isUser ? 'items-end' : 'items-start'}`}>

          {!isUser && (
            <div className="flex items-center gap-2">
              <span className={`text-[13px] font-medium ${darkMode ? 'text-gray-200' : 'text-gray-800'}`}>
                GREEN AI
              </span>
              {message.webSearch && (
                <span
                  className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-medium border"
                  style={{
                    color: '#10b981',
                    backgroundColor: darkMode ? 'rgba(16,185,129,0.12)' : 'rgba(16,185,129,0.08)',
                    borderColor: darkMode ? 'rgba(16,185,129,0.3)' : 'rgba(16,185,129,0.25)',
                  }}
                >
                  <Globe size={10} />
                  Searched the web
                </span>
              )}
            </div>
          )}

          {isUser ? (
            <div className={`px-4 py-2.5 rounded-[18px] rounded-tr-[4px] text-[15px] leading-relaxed ${
              darkMode
                ? 'bg-gray-700 text-gray-100 border border-gray-600'
                : 'bg-gray-100 text-gray-900 border border-gray-200'
            }`}>
              {message.text}
            </div>
          ) : (
            <div className={`${darkMode ? 'text-gray-100' : 'text-gray-900'}`}>
              {renderMarkdown(message.text, darkMode)}
            </div>
          )}

          {!isUser && (
            <div className="flex items-center gap-1 mt-1 opacity-0 group-hover:opacity-100 transition-opacity duration-150">

              {/* Copy */}
              <button
                onClick={handleCopy}
                className={`flex items-center gap-1.5 px-2 py-1 rounded-md text-xs border transition-colors ${
                  darkMode
                    ? 'border-gray-600 text-gray-400 hover:text-gray-100 hover:bg-gray-700'
                    : 'border-gray-200 text-gray-500 hover:text-gray-800 hover:bg-gray-100'
                }`}
              >
                {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
                {copied ? 'Copied' : 'Copy'}
              </button>

              {/* Download */}
              <div className="relative group/download">
                <button
                  className={`p-1.5 rounded-md border text-xs transition-colors ${
                    darkMode
                      ? 'border-gray-600 text-gray-400 hover:text-green-400 hover:bg-gray-700'
                      : 'border-gray-200 text-gray-500 hover:text-green-600 hover:bg-gray-100'
                  }`}
                >
                  <Download className="w-3 h-3" />
                </button>

                <div className={`absolute bottom-full left-0 mb-1 opacity-0 group-hover/download:opacity-100 transition-opacity duration-150 ${
                  darkMode ? 'bg-gray-800 border-gray-600' : 'bg-white border-gray-200'
                } border rounded-lg shadow-lg p-1 min-w-[120px] z-10`}>
                  <button
                    onClick={() => downloadAsPDF(message.text)}
                    className={`w-full text-left px-2 py-1.5 text-xs rounded transition-colors ${
                      darkMode
                        ? 'text-gray-300 hover:text-white hover:bg-gray-700'
                        : 'text-gray-700 hover:text-gray-900 hover:bg-gray-100'
                    }`}
                  >
                    Download as PDF
                  </button>
                  <button
                    onClick={() => downloadAsDoc(message.text)}
                    className={`w-full text-left px-2 py-1.5 text-xs rounded transition-colors ${
                      darkMode
                        ? 'text-gray-300 hover:text-white hover:bg-gray-700'
                        : 'text-gray-700 hover:text-gray-900 hover:bg-gray-100'
                    }`}
                  >
                    Download as DOC
                  </button>
                </div>
              </div>

              {/* Like */}
              <button
                onClick={() => onReaction(message.id, 'like')}
                className={`p-1.5 rounded-md border text-xs transition-colors ${
                  message.liked
                    ? 'border-emerald-500/40 text-emerald-500'
                    : darkMode
                      ? 'border-gray-600 text-gray-400 hover:text-emerald-400 hover:bg-gray-700'
                      : 'border-gray-200 text-gray-500 hover:text-emerald-600 hover:bg-gray-100'
                }`}
              >
                <ThumbsUp className="w-3 h-3" />
              </button>

              {/* Dislike */}
              <button
                onClick={() => onReaction(message.id, 'dislike')}
                className={`p-1.5 rounded-md border text-xs transition-colors ${
                  message.disliked
                    ? 'border-red-500/40 text-red-500'
                    : darkMode
                      ? 'border-gray-600 text-gray-400 hover:text-red-400 hover:bg-gray-700'
                      : 'border-gray-200 text-gray-500 hover:text-red-600 hover:bg-gray-100'
                }`}
              >
                <ThumbsDown className="w-3 h-3" />
              </button>

            </div>
          )}
        </div>
      </div>
    </div>
  );
};